name: Build ASI Mod

on: [push]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1
      
    - name: Compile
      run: |
        cl /nologo /LD /FeRadmirMod.asi main.cpp /link user32.lib wininet.lib shlwapi.lib
        
    - uses: actions/upload-artifact@v4
      with:
        name: RadmirMod.asi
        path: RadmirMod.asi
