name: Build DLL
on: [push]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up MinGW
      run: |
        choco install mingw -y
        echo "C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin" >> $GITHUB_PATH
        
    - name: Compile DLL
      run: |
        x86_64-w64-mingw32-g++ -shared -o RadmirMod.dll main.cpp -lwininet -static -std=c++17 -I/mingw64/include -L/mingw64/lib
        
    - uses: actions/upload-artifact@v4
      with:
        name: RadmirMod.dll
        path: RadmirMod.dll
