name: Build ASI Plugin

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Build ASI
      run: |
        mkdir build
        cd build
        cmake -G "Visual Studio 16 2019" ..
        cmake --build . --config Release
        cp Release/ResourceLoader.asi ../dist/

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: ResourceLoader.asi
        path: dist/ResourceLoader.asi
